apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Values.cluster.name }}
  labels:
    {{- include "cloudnativepg.labels" . | nindent 4 }}
spec:
  instances: {{ .Values.cluster.instances }}
  imageName: {{ .Values.cluster.imageName }}
  
  storage:
    size: {{ .Values.cluster.storage.size }}
    {{- if .Values.cluster.storage.storageClass }}
    storageClass: {{ .Values.cluster.storage.storageClass }}
    {{- end }}
  
  bootstrap:
    initdb:
      database: {{ .Values.cluster.bootstrap.initdb.database }}
      owner: {{ .Values.cluster.bootstrap.initdb.owner }}
      {{- if .Values.cluster.bootstrap.initdb.secret.name }}
      secret:
        name: {{ .Values.cluster.bootstrap.initdb.secret.name }}
      {{- end }}
  
  {{- if .Values.cluster.monitoring.enabled }}
  monitoring:
    enablePodMonitor: true
  {{- end }}
  
  {{- if .Values.cluster.resources }}
  resources:
    {{- toYaml .Values.cluster.resources | nindent 4 }}
  {{- end }}
