apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "azure-microservice.fullname" . }}
  labels:
    {{- include "azure-microservice.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "azure-microservice.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- if .Values.workloadIdentity.enabled }}
        azure.workload.identity/use: "true"
        {{- end }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "azure-microservice.selectorLabels" . | nindent 8 }}
        {{- if .Values.workloadIdentity.enabled }}
        azure.workload.identity/use: "true"
        {{- end }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "azure-microservice.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ include "azure-microservice.containerPort" . }}
          protocol: TCP
        {{- if .Values.metrics.enabled }}
        - name: metrics
          containerPort: {{ .Values.metrics.port }}
          protocol: TCP
        {{- end }}
        env:
        {{- if .Values.workloadIdentity.enabled }}
        - name: AZURE_CLIENT_ID
          valueFrom:
            configMapKeyRef:
              name: {{ include "azure-microservice.fullname" . }}-identity
              key: AZURE_CLIENT_ID
        {{- end }}
        {{- if and .Values.azureKeyVault.enabled .Values.azureKeyVault.create }}
        - name: AZURE_KEYVAULT_URI
          valueFrom:
            configMapKeyRef:
              name: {{ include "azure-microservice.fullname" . }}-keyvault
              key: AZURE_KEYVAULT_URI
        {{- end }}
        {{- if and .Values.azureAppConfiguration.enabled .Values.azureAppConfiguration.create }}
        - name: AZURE_APPCONFIG_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: {{ include "azure-microservice.fullname" . }}-appconfig
              key: AZURE_APPCONFIG_ENDPOINT
        {{- end }}
        {{- if and .Values.azureServiceBus.enabled .Values.azureServiceBus.create }}
        - name: AZURE_SERVICEBUS_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: {{ include "azure-microservice.fullname" . }}-servicebus
              key: AZURE_SERVICEBUS_ENDPOINT
        {{- end }}
        {{- if .Values.azureApplicationInsights.enabled }}
        - name: APPLICATIONINSIGHTS_CONNECTION_STRING
          value: {{ .Values.azureApplicationInsights.connectionString | quote }}
        - name: APPINSIGHTS_INSTRUMENTATIONKEY
          value: {{ .Values.azureApplicationInsights.instrumentationKey | quote }}
        {{- end }}
        {{- with .Values.env }}
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.envFrom }}
        envFrom:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- if .Values.livenessProbe }}
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 10 }}
        {{- end }}
        {{- if .Values.readinessProbe }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 10 }}
        {{- end }}
        {{- if .Values.startupProbe }}
        startupProbe:
          {{- toYaml .Values.startupProbe | nindent 10 }}
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        volumeMounts:
        - mountPath: /var/run/secrets/azure/tokens/azure-identity-token
          name: azure-identity-token
          readOnly: true
        {{- if .Values.azureKeyVault.enabled }}
        - name: secrets-store
          mountPath: "/mnt/secrets-store"
          readOnly: true
        {{- end }}
        {{- with .Values.volumeMounts }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      volumes:
      - name: azure-identity-token
        projected:
          defaultMode: 420
          sources:
            - serviceAccountToken:
                audience: api://AzureADTokenExchange
                expirationSeconds: 3600
                path: azure-identity
      {{- if .Values.azureKeyVault.enabled }}
      - name: secrets-store
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: {{ include "azure-microservice.fullname" . }}-keyvault
      {{- end }}
      {{- with .Values.volumes }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
