{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "azure-microservice.serviceAccountName" . }}
  labels:
    {{- include "azure-microservice.labels" . | nindent 4 }}
    {{- if .Values.workloadIdentity.enabled }}
    azure.workload.identity/use: "true"
    {{- end }}
  annotations:
    {{- if .Values.workloadIdentity.enabled }}
    azure.workload.identity/client-id: "{{ "{{" }} index (lookup "v1" "ConfigMap" .Release.Namespace (printf "%s-identity" (include "azure-microservice.fullname" .))) "data" "AZURE_CLIENT_ID" | default "" {{ "}}" }}"
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
