{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "azure-microservice.fullname" . }}
  labels:
    {{- include "azure-microservice.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "azure-microservice.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: metrics
    path: {{ .Values.metrics.path }}
    interval: {{ .Values.metrics.serviceMonitor.interval }}
{{- end }}
