{{- if .Values.appConfig.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backstage-pg.fullname" . }}-app-config
  labels:
    {{- include "backstage-pg.labels" . | nindent 4 }}
data:
  app-config.yaml: |
    {{- toYaml .Values.backstage | nindent 4 }}
    
{{- end }}
