apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backstage-pg.fullname" . }}
  labels:
    {{- include "backstage-pg.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "backstage-pg.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "backstage-pg.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "backstage-pg.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: backstage
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.backstage.backend.listen.port }}
          protocol: TCP
        env:
        - name: POSTGRES_HOST
          value: {{ include "backstage-pg.postgresql.host" . }}
        - name: POSTGRES_PORT
          value: {{ .Values.backstage.backend.database.connection.port | quote }}
        - name: POSTGRES_USER
          value: {{ .Values.postgresql.auth.username }}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "backstage-pg.postgresql.secretName" . }}
              key: password
        - name: NODE_ENV
          value: "production"
        {{- if .Values.githubApp.enabled }}
        - name: AUTH_ORG_APP_ID
          valueFrom:
            secretKeyRef:
              name: {{ .Values.githubApp.secretName }}
              key: app-id
        - name: AUTH_ORG_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: {{ .Values.githubApp.secretName }}
              key: client-id
        - name: AUTH_ORG_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ .Values.githubApp.secretName }}
              key: client-secret
        - name: AUTH_ORG1_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.githubApp.secretName }}
              key: private-key
        - name: AUTH_ORG_WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ .Values.githubApp.secretName }}
              key: webhook-secret
        {{- end }}
        {{- with .Values.extraEnvVars }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.extraEnvFrom }}
        envFrom:
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.livenessProbe }}
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 10 }}
        {{- end }}
        {{- if .Values.readinessProbe }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 10 }}
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        volumeMounts:
        - name: app-config
          mountPath: /app/app-config.yaml
          subPath: app-config.yaml
        {{- with .Values.volumeMounts }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      volumes:
      - name: app-config
        configMap:
          name: {{ if .Values.appConfig.existingConfigMap }}{{ .Values.appConfig.existingConfigMap }}{{ else }}{{ include "backstage-pg.fullname" . }}-app-config{{ end }}
      {{- with .Values.volumes }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
