{{- if .Values.githubApp.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.githubApp.secretName }}
  labels:
    {{- include "backstage-pg.labels" . | nindent 4 }}
type: Opaque
data:
  app-id: {{ .Values.githubApp.appId | b64enc | quote }}
  client-id: {{ .Values.githubApp.clientId | b64enc | quote }}
  client-secret: {{ .Values.githubApp.clientSecret | b64enc | quote }}
  private-key: {{ .Values.githubApp.privateKey | b64enc | quote }}
  webhook-secret: {{ .Values.githubApp.webhookSecret | b64enc | quote }}
{{- end }}
