{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgresql.cluster.name }}-app
  labels:
    {{- include "backstage-pg.labels" . | nindent 4 }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.postgresql.auth.username }}
  {{- if .Values.postgresql.auth.password }}
  password: {{ .Values.postgresql.auth.password }}
  {{- else }}
  password: {{ randAlphaNum 32 }}
  {{- end }}
{{- end }}
