apiVersion: v1
kind: Secret
metadata:
  name: github-app-credentials
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "backstage.labels" . | nindent 4 }}
type: Opaque
data:
  AUTH_ORG_APP_ID: {{ .Values.github.appId }}
  AUTH_ORG_CLIENT_ID: {{ .Values.github.clientId }}
  AUTH_ORG_CLIENT_SECRET: {{ .Values.github.clientSecret }}
  AUTH_ORG1_PRIVATE_KEY: {{ .Values.github.privateKey }}
  AUTH_ORG_WEBHOOK_SECRET: {{ .Values.github.webhookSecret }}
